name: Sequential jobs
on: push
jobs:
  first: # 依存ジョブがないので最初に実行される
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job"
  second: # firstジョブの後に実行
    runs-on: ubuntu-latest
    needs: [first] # 依存するジョブのIDを渡す
    steps:
      - run: sleep 10 && echo "Second job"
  third: # secondジョブの後に実行
    runs-on: ubuntu-latest
    needs: [second]
    steps:
      - run: sleep 10 && echo "Third job"
