name: Test
on:
  pull_request:
    paths: ["go/**/*.go"] # goのファイル変更時のみ起動
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # リポジトリからソースコードへアクセスするときに必要
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - run: go test go/excellent/*.go
